//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolucional.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota
    {
        public int id_aluno { get; set; }
        public Nullable<decimal> matematica { get; set; }
        public Nullable<decimal> portugues { get; set; }
        public Nullable<decimal> historia { get; set; }
        public Nullable<decimal> geografica { get; set; }
        public Nullable<decimal> ingles { get; set; }
        public Nullable<decimal> biologia { get; set; }
        public Nullable<decimal> filosofia { get; set; }
        public Nullable<decimal> fisica { get; set; }
        public Nullable<decimal> quimica { get; set; }
    }
}
